const studentData = {
  school: "ALTASFIYAH TAHFEEZ AND ISLAMIYAH SCHOOL, ABUJA",
  studentName: "SAMBO MUHAMMAD MALAMIYO",
  class: "NURSERY CLASS 1",
  term: "FIRST TERM",
  session: "ACADEMIC YEAR 2024/2025",
  admissionNo: "ATBS/N1/2017/005",
  age: 6,
  sex: "Male",
  house: "A",
  noInClass: 7,
  totalScore: 508,
  avgScore: 72.57,
  classHighest: 580,
  classLowest: 372,
  classPos: "1st",
  overallGrade: "A",
  overallRemark: "EXCELLENT",
  subjects: [
    { name: "QUR'AN", CA1: 5, CA2: 6, Exam: 59, Total: 75, Position: "2nd", Grade: "A", Remark: "EXCELLENT" },
    { name: "ARABIC LANGUAGE", CA1: 7, CA2: 5, Exam: 54, Total: 74, Position: "4th", Grade: "A", Remark: "EXCELLENT" },
    { name: "HURUF", CA1: 10, CA2: 8, Exam: 54, Total: 79, Position: "2nd", Grade: "A", Remark: "EXCELLENT" },
    { name: "ISLAMIC STUDIES", CA1: 5, CA2: 8, Exam: 54, Total: 73, Position: "4th", Grade: "A", Remark: "EXCELLENT" },
    { name: "MORAL ETHICS", CA1: 10, CA2: 6, Exam: 51, Total: 72, Position: "3rd", Grade: "A", Remark: "EXCELLENT" },
  ],
  behavior: {
    moralEthics: "EXCELLENT",
    punctuality: "GOOD",
    handWriting: "GOOD",
    honesty: "GOOD",
    fluency: "GOOD",
    selfControl: "GOOD",
    responsibility: "GOOD",
    initiative: "GOOD",
    politeness: "GOOD"
  },
  headRemark: "An excellent result, keep up the good work",
  classTeacherRemark: "A hardworking learner and shows respect"
};
